# Generated by Django 3.1.6 on 2021-02-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('status', models.CharField(default='not_runned', max_length=200)),
                ('version', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Syntax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=200)),
                ('version', models.IntegerField(default=0)),
                ('err_text', models.CharField(max_length=1000)),
                ('score', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.progs')),
            ],
        ),
    ]
