# Generated by Django 3.1.7 on 2021-04-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_syntax_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='syntax',
            name='test_passed',
            field=models.BooleanField(default=False),
        ),
    ]
